package com.demo.greendaotest.chat.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "chat_group".
 */
public class ChatGroup implements java.io.Serializable {

    private Long id;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ChatGroup() {
    }

    public ChatGroup(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
